/* eslint-disable */
import * as Types from './graphql.generated';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type TabLayoutQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type TabLayoutQuery = (
  { __typename: 'Query', aiFramework: string }
  & { ' $fragmentRefs'?: { 'Omnibar_QueryFragment': Omnibar_QueryFragment } }
);

export type PlaceListItem_PlaceFragment = { __typename: 'Place', id: string, formattedAddress: string, isBookmarked: boolean, displayName: { __typename: 'LocalizedText', text: string, languageCode: string } } & { ' $fragmentName'?: 'PlaceListItem_PlaceFragment' };

export type ScheduleListItem_SchedSessionFragment = { __typename: 'SchedSession', id: string, name: string, isBookmarked: boolean, start_time: string, end_time: string, type: string, subtype: string | null, venue: { __typename: 'SchedVenue', id: string, name: string | null } | null, speakers: Array<{ __typename: 'SchedSpeaker', id: string, username: string, name: string }> } & { ' $fragmentName'?: 'ScheduleListItem_SchedSessionFragment' };

export type SpeakerListItem_SchedSpeakerFragment = { __typename: 'SchedSpeaker', id: string, name: string, company: string, position: string, avatar: string, isBookmarked: boolean } & { ' $fragmentName'?: 'SpeakerListItem_SchedSpeakerFragment' };

export type Omnibar_QueryFragment = { aiFramework: string } & { ' $fragmentName'?: 'Omnibar_QueryFragment' };

export type PlaceMarkerInfoFragment = { __typename: 'Place', id: string, displayName: { __typename: 'LocalizedText', text: string, languageCode: string }, location: { __typename: 'LatLng', latitude: number, longitude: number }, primaryTypeDisplayName: { __typename: 'LocalizedText', text: string, languageCode: string } | null } & { ' $fragmentName'?: 'PlaceMarkerInfoFragment' };

export const PlaceListItem_PlaceFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaceListItem_Place"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Place"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"languageCode"}}]}},{"kind":"Field","name":{"kind":"Name","value":"formattedAddress"}},{"kind":"Field","name":{"kind":"Name","value":"isBookmarked"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]}]}}]} as unknown as DocumentNode<PlaceListItem_PlaceFragment, unknown>;
export const ScheduleListItem_SchedSessionFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ScheduleListItem_SchedSession"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"isBookmarked"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]},{"kind":"Field","name":{"kind":"Name","value":"venue"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"start_time"}},{"kind":"Field","name":{"kind":"Name","value":"end_time"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"subtype"}},{"kind":"Field","name":{"kind":"Name","value":"speakers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]} as unknown as DocumentNode<ScheduleListItem_SchedSessionFragment, unknown>;
export const SpeakerListItem_SchedSpeakerFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SpeakerListItem_SchedSpeaker"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedSpeaker"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"company"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"avatar"}},{"kind":"Field","name":{"kind":"Name","value":"isBookmarked"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]}]}}]} as unknown as DocumentNode<SpeakerListItem_SchedSpeakerFragment, unknown>;
export const Omnibar_QueryFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"Omnibar_Query"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Query"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"aiFramework"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]}]}}]} as unknown as DocumentNode<Omnibar_QueryFragment, unknown>;
export const PlaceMarkerInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaceMarkerInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Place"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"displayName"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"languageCode"}}]}},{"kind":"Field","name":{"kind":"Name","value":"location"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"latitude"}},{"kind":"Field","name":{"kind":"Name","value":"longitude"}}]}},{"kind":"Field","name":{"kind":"Name","value":"primaryTypeDisplayName"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"text"}},{"kind":"Field","name":{"kind":"Name","value":"languageCode"}}]}}]}}]} as unknown as DocumentNode<PlaceMarkerInfoFragment, unknown>;
export const TabLayoutDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"TabLayout"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"Omnibar_Query"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"unmask"}}]},{"kind":"FragmentSpread","name":{"kind":"Name","value":"Omnibar_Query"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"Omnibar_Query"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Query"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"aiFramework"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]}]}}]} as unknown as DocumentNode<TabLayoutQuery, TabLayoutQueryVariables>;