/* eslint-disable */
import * as Types from '../../graphql.generated';

import { SectionHeader_SchedEventFragment } from './SectionHeader.generated';
import { ScheduleListItem_SchedSessionFragment } from './ScheduleItem.generated';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ScheduleList_QueryFragment = { schedule_2025: Array<(
    { __typename: 'SchedSession', id: string, event: { __typename: 'SchedEvent', start_time_epoch: number | null, start_weekday: string | null, start_time: string | null } | null, venue: { __typename: 'SchedVenue', id: string } | null }
    & { ' $fragmentRefs'?: { 'ScheduleListItem_SchedSessionFragment': ScheduleListItem_SchedSessionFragment } }
  )> | null } & { ' $fragmentName'?: 'ScheduleList_QueryFragment' };

export const ScheduleList_QueryFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ScheduleList_Query"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Query"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"schedule_2025"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"event"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"start_time_epoch"}},{"kind":"Field","name":{"kind":"Name","value":"start_weekday"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"SectionHeader_SchedEvent"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"unmask"}}]}]}},{"kind":"Field","name":{"kind":"Name","value":"venue"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"ScheduleListItem_SchedSession"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SectionHeader_SchedEvent"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedEvent"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"start_time"}},{"kind":"Field","name":{"kind":"Name","value":"start_weekday"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ScheduleListItem_SchedSession"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"venue"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"event"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"start_time"}},{"kind":"Field","name":{"kind":"Name","value":"end_time"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"subtype"}}]}},{"kind":"Field","name":{"kind":"Name","value":"speakers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]} as unknown as DocumentNode<ScheduleList_QueryFragment, unknown>;