/* eslint-disable */
import * as Types from '../../../graphql.generated';

import { ScheduleListItem_SessionFragment } from '../../../components/ListItems/ScheduleListItem.generated';
import { SectionHeader_EventFragment } from './SectionHeader.generated';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ScheduleList_EventFragment = { __typename: 'SchedEvent', id: string, sessions: Array<(
    { __typename: 'SchedSession', id: string, start_time_ts: number | null, venue: { __typename: 'SchedVenue', id: string } | null }
    & { ' $fragmentRefs'?: { 'ScheduleListItem_SessionFragment': ScheduleListItem_SessionFragment;'SectionHeader_EventFragment': SectionHeader_EventFragment } }
  )> } & { ' $fragmentName'?: 'ScheduleList_EventFragment' };

export const ScheduleList_EventFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ScheduleList_event"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedEvent"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"sessions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"start_time_ts"}},{"kind":"Field","name":{"kind":"Name","value":"venue"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"ScheduleListItem_session"}},{"kind":"FragmentSpread","name":{"kind":"Name","value":"SectionHeader_event"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"ScheduleListItem_session"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"isBookmarked"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]},{"kind":"Field","name":{"kind":"Name","value":"venue"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"start_time"}},{"kind":"Field","name":{"kind":"Name","value":"end_time"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"subtype"}},{"kind":"Field","name":{"kind":"Name","value":"speakers"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"SectionHeader_event"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"SchedSession"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"start_time"}},{"kind":"Field","name":{"kind":"Name","value":"start_time_ts"}}]}}]} as unknown as DocumentNode<ScheduleList_EventFragment, unknown>;