import { Types } from "@graphql-codegen/plugin-helpers";
import type { TypeScriptDocumentsPluginConfig } from "@graphql-codegen/typescript-operations";
import type { TypeScriptTypedDocumentNodesConfig as TypedDocumentNodeConfig } from "@graphql-codegen/typed-document-node";

type PluginConfig = TypeScriptDocumentsPluginConfig & TypedDocumentNodeConfig;

const sharedConfig: PluginConfig = {
  avoidOptionals: {
    // Use `null` for nullable fields instead of optionals
    field: true,
    // Allow nullable input fields to remain unspecified
    inputValue: false,
  },
  // Use `unknown` instead of `any` for unconfigured scalars
  defaultScalarType: "unknown",
  // Apollo Client always includes `__typename` fields
  nonOptionalTypename: true,
  // Apollo Client doesn't add the `__typename` field to root types so
  // don't generate a type for the `__typename` for root operation types.
  skipTypeNameForRoot: true,
  inlineFragmentTypes: "mask",
  includeExternalFragments: false,
  customDirectives: {
    apolloUnmask: true,
  },
};

const supergraphSchema = ["http://localhost:4000"];
const fullSchema = [
  ...supergraphSchema,
  "./src/localSchema.ts",
  "./src/localSchema.*.ts",
];

const config: Types.Config = {
  overwrite: true,
  // Don't exit with non-zero status when there are no documents
  ignoreNoDocuments: true,
  generates: {
    "./src/schema.json": {
      schema: fullSchema,
      plugins: ["introspection"],
      config: {
        minify: false,
      },
    },
    "../connector/supergraph.graphqls": {
      plugins: ["schema-ast"],
      schema: supergraphSchema,
    },
    "./src/graphql.generated.ts": {
      schema: fullSchema,
      plugins: [
        {
          add: {
            content: "/* eslint-disable */",
          },
        },
        "typescript",
      ],
    },
    "./src/": {
      schema: fullSchema,
      documents: ["src/**/*.{ts,tsx}", "!src/app/**/*.{ts,tsx}"],
      preset: "near-operation-file",
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: "./graphql.generated.ts",
      },
      plugins: [
        {
          add: {
            content: "/* eslint-disable */",
          },
        },
        "typescript-operations",
        "typed-document-node",
      ],
      config: sharedConfig,
    },
    "./src/app-queries.generated.ts": {
      schema: fullSchema,
      documents: [
        // We only want to include queries used in the app directory
        "src/app/**/*.{ts,tsx}",
        // But they might reference fragments from the components directory
        "src/components/**/*.{ts,tsx}",
      ],
      preset: "import-types",
      presetConfig: {
        typesPath: "./graphql.generated",
      },
      plugins: [
        {
          add: {
            content: "/* eslint-disable */",
          },
        },
        "typescript-operations",
        "typed-document-node",
      ],
      config: {
        ...sharedConfig,
        // would also like this to not create runtime code for fragments, but that seems impossible
      } satisfies PluginConfig,
    },
  },
};

export default config;
